[project]
name = "penpal"
version = "1.0.0"
authors = [
    {name = "Wolfgang Hotwagner", email = "wolfgang.hotwagner@ait.ac.at"},
]
description = "PenPal is an attack orchestration tool that executes full attack-chains based on playbooks."
readme = "README.md"
requires-python = ">=3.7"
keywords = ["Pentest", "Attack", "Orchestration", "Hacking", "Simulating", "Attackchain"]
license = {text = "GPL-3.0"}
dependencies = [
    "pydantic",
    "colorlog",
    "pymetasploit3",
    "pyaml",
    "paramiko"
]
dynamic = ["version"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
